// Code generated by apigen. DO NOT EDIT.

import {
  Apigen as ApigenBase,
  type DbInput,
  type Relation,
  relation as relationBase,
} from '@repo/apigen';

export const catalog = {
  customers: {
    id: 'uuid',
    email: 'text',
    api_token: 'text',
    created_at: 'timestamptz',
  },
  order_items: {
    id: 'int8',
    order_id: 'int8',
    product_id: 'int8',
    quantity: 'int4',
    unit_price: 'numeric',
  },
  orders: {
    id: 'int8',
    customer_id: 'uuid',
    status: 'text',
    total: 'numeric',
    placed_at: 'timestamptz',
  },
  products: {
    id: 'int8',
    sku: 'text',
    name: 'text',
    price: 'numeric',
    in_stock: 'bool',
    attributes: 'jsonb',
    added_on: 'date',
  },
} as const;

export type Catalog = typeof catalog;

export interface Customers {
  id: string;
  email: string;
  api_token: string;
  created_at: string;
}

export interface OrderItems {
  id: string;
  order_id: string;
  product_id: string;
  quantity: number;
  unit_price: string;
}

export interface Orders {
  id: string;
  customer_id: string;
  status: string;
  total: string;
  placed_at: string;
}

export interface Products {
  id: string;
  sku: string;
  name: string;
  price: string;
  in_stock: boolean;
  attributes: unknown;
  added_on: string;
}

type ColumnsOf<R extends keyof Catalog> = Extract<keyof Catalog[R], string>;

export function relation<R extends keyof Catalog & string>(name: R): Relation<ColumnsOf<R>> {
  return relationBase<ColumnsOf<R>>(name);
}

export class Apigen extends ApigenBase {
  constructor(options: { db: DbInput }) {
    super({ db: options.db, catalog });
  }
}
