// Code generated by apigen. DO NOT EDIT.

import {
  Apigen as ApigenBase,
  type DbInput,
  type Func,
  func as funcBase,
  type Relation,
  relation as relationBase,
} from '@repo/apigen';

export const catalog = {
  todos: {
    id: 'int8',
    owner: 'uuid',
    title: 'text',
    done: 'bool',
  },
} as const;

export type Catalog = typeof catalog;

export const functions = {
  add_numbers: {
    a: 'int4',
    b: 'int4',
  },
  count_todos: {
    owner_id: 'uuid',
  },
  greet: {
    name: 'text',
    excited: 'bool',
  },
  series: {
    n: 'int4',
  },
  whoami: {},
} as const;

export type Functions = typeof functions;

export interface Todos {
  id: string;
  owner: string;
  title: string;
  done: boolean;
}

type ColumnsOf<R extends keyof Catalog> = Extract<keyof Catalog[R], string>;

export function relation<R extends keyof Catalog & string>(name: R): Relation<ColumnsOf<R>> {
  return relationBase<ColumnsOf<R>>(name);
}

export function func<F extends keyof Functions & string>(name: F): Func {
  return funcBase(name);
}

export class Apigen extends ApigenBase {
  constructor(options: { db: DbInput }) {
    super({ db: options.db, catalog, functions });
  }
}
