// Code generated by apigen. DO NOT EDIT.

import {
  Apigen as ApigenBase,
  type DbInput,
  type Func,
  func as funcBase,
  type Relation,
  relation as relationBase,
} from '@repo/apigen';

export const catalog = {
  videos: {
    id: 'int8',
    title: 'text',
    content_type: 'text',
    loid: 'oid',
    byte_size: 'int8',
  },
} as const;

export type Catalog = typeof catalog;

export const functions = {
  video_chunk: {
    id: 'int8',
    range_start: 'int8',
    range_length: 'int4',
  },
} as const;

export type Functions = typeof functions;

export interface Videos {
  id: string;
  title: string;
  content_type: string;
  loid: number;
  byte_size: string;
}

type ColumnsOf<R extends keyof Catalog> = Extract<keyof Catalog[R], string>;

export function relation<R extends keyof Catalog & string>(name: R): Relation<ColumnsOf<R>> {
  return relationBase<ColumnsOf<R>>(name);
}

export function func<F extends keyof Functions & string>(name: F): Func {
  return funcBase(name);
}

export class Apigen extends ApigenBase {
  constructor(options: { db: DbInput }) {
    super({ db: options.db, catalog, functions });
  }
}
