// Code generated by apigen. DO NOT EDIT.

import {
  Apigen as ApigenBase,
  type DbInput,
  type Relation,
  relation as relationBase,
} from '@repo/apigen';

export const catalog = {
  todos: {
    id: 'int8',
    owner: 'uuid',
    title: 'text',
    done: 'bool',
    priority: 'int4',
    notes: 'text',
  },
} as const;

export type Catalog = typeof catalog;

export const primaryKeys = {
  todos: ['id'],
} as const;

export const foreignKeys = {
  todos: [],
} as const;

export interface Todos {
  id: string;
  owner: string;
  title: string;
  done: boolean;
  priority: number;
  notes: string | null;
}

type ColumnsOf<R extends keyof Catalog> = Extract<keyof Catalog[R], string>;

export function relation<R extends keyof Catalog & string>(name: R): Relation<ColumnsOf<R>> {
  return relationBase<ColumnsOf<R>>(name);
}

export class Apigen extends ApigenBase {
  constructor(options: { db: DbInput }) {
    super({ db: options.db, catalog, primaryKeys, foreignKeys });
  }
}
