import type { FunctionIntrospection, Introspection } from './introspect.js';
import { tsTypeFor } from './pg-types.js';

const DEFAULT_SPECIFIER = '@ilbertt/apigen';
const IDENT_RE = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;

/** A property key: bare when a valid identifier, single-quoted otherwise. */
function propKey(name: string): string {
  return IDENT_RE.test(name) ? name : `'${name.replaceAll("'", "\\'")}'`;
}

function pascalCase(name: string): string {
  return name
    .split(/[^a-zA-Z0-9]+/)
    .filter((part) => part.length > 0)
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join('');
}

function catalogLiteral({
  introspection,
  tables,
}: {
  introspection: Introspection;
  tables: string[];
}): string {
  return tables
    .map((table) => {
      const cols = introspection[table] ?? [];
      const entries = cols.map((c) => `    ${propKey(c.name)}: '${c.pgType}',`).join('\n');
      return `  ${propKey(table)}: {\n${entries}\n  },`;
    })
    .join('\n');
}

function functionsLiteral({
  functions,
  functionNames,
}: {
  functions: FunctionIntrospection;
  functionNames: string[];
}): string {
  return functionNames
    .map((name) => {
      const args = functions[name]?.args ?? [];
      if (args.length === 0) {
        return `  ${propKey(name)}: {},`;
      }
      const entries = args.map((a) => `    ${propKey(a.name)}: '${a.pgType}',`).join('\n');
      return `  ${propKey(name)}: {\n${entries}\n  },`;
    })
    .join('\n');
}

function rowTypes({
  introspection,
  tables,
}: {
  introspection: Introspection;
  tables: string[];
}): string {
  return tables
    .map((table) => {
      const cols = introspection[table] ?? [];
      const fields = cols
        .map((c) => `  ${propKey(c.name)}: ${tsTypeFor(c.pgType)}${c.nullable ? ' | null' : ''};`)
        .join('\n');
      return `export interface ${pascalCase(table)} {\n${fields}\n}`;
    })
    .join('\n\n');
}

/**
 * Render `api.gen.ts`: the catalog value, row types, and catalog-bound `relation` +
 * `Apigen`. When the schema has functions, also emit the `functions` catalog and a
 * catalog-bound `func` factory. The functions machinery is omitted entirely when
 * there are none, so a function-free schema generates exactly as before.
 */
export function emit({
  introspection,
  functions = {},
  moduleSpecifier = DEFAULT_SPECIFIER,
}: {
  introspection: Introspection;
  functions?: FunctionIntrospection;
  moduleSpecifier?: string;
}): string {
  const tables = Object.keys(introspection).sort();
  const functionNames = Object.keys(functions).sort();
  const hasFunctions = functionNames.length > 0;

  const imports = [
    'Apigen as ApigenBase,',
    'type DbInput,',
    ...(hasFunctions ? ['type Func,', 'func as funcBase,'] : []),
    'type Relation,',
    'relation as relationBase,',
  ]
    .map((line) => `  ${line}`)
    .join('\n');

  const functionsBlock = hasFunctions
    ? `\nexport const functions = {\n${functionsLiteral({ functions, functionNames })}\n} as const;\n\nexport type Functions = typeof functions;\n`
    : '';

  const funcFactory = hasFunctions
    ? `\nexport function func<F extends keyof Functions & string>(name: F): Func {\n  return funcBase(name);\n}\n`
    : '';

  const superArgs = hasFunctions
    ? '{ db: options.db, catalog, functions }'
    : '{ db: options.db, catalog }';

  return `// Code generated by apigen. DO NOT EDIT.

import {
${imports}
} from '${moduleSpecifier}';

export const catalog = {
${catalogLiteral({ introspection, tables })}
} as const;

export type Catalog = typeof catalog;
${functionsBlock}
${rowTypes({ introspection, tables })}

type ColumnsOf<R extends keyof Catalog> = Extract<keyof Catalog[R], string>;

export function relation<R extends keyof Catalog & string>(name: R): Relation<ColumnsOf<R>> {
  return relationBase<ColumnsOf<R>>(name);
}
${funcFactory}
export class Apigen extends ApigenBase {
  constructor(options: { db: DbInput }) {
    super(${superArgs});
  }
}
`;
}
