import type { Introspection } from './introspect.js';
import { tsTypeFor } from './pg-types.js';

const DEFAULT_SPECIFIER = '@ilbertt/apigen';
const IDENT_RE = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;

/** A property key: bare when a valid identifier, single-quoted otherwise. */
function propKey(name: string): string {
  return IDENT_RE.test(name) ? name : `'${name.replaceAll("'", "\\'")}'`;
}

function pascalCase(name: string): string {
  return name
    .split(/[^a-zA-Z0-9]+/)
    .filter((part) => part.length > 0)
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join('');
}

function catalogLiteral({
  introspection,
  tables,
}: {
  introspection: Introspection;
  tables: string[];
}): string {
  return tables
    .map((table) => {
      const cols = introspection[table] ?? [];
      const entries = cols.map((c) => `    ${propKey(c.name)}: '${c.pgType}',`).join('\n');
      return `  ${propKey(table)}: {\n${entries}\n  },`;
    })
    .join('\n');
}

function rowTypes({
  introspection,
  tables,
}: {
  introspection: Introspection;
  tables: string[];
}): string {
  return tables
    .map((table) => {
      const cols = introspection[table] ?? [];
      const fields = cols
        .map((c) => `  ${propKey(c.name)}: ${tsTypeFor(c.pgType)}${c.nullable ? ' | null' : ''};`)
        .join('\n');
      return `export interface ${pascalCase(table)} {\n${fields}\n}`;
    })
    .join('\n\n');
}

/** Render `api.gen.ts`: the catalog value, row types, and catalog-bound `relation` + `Apigen`. */
export function emit({
  introspection,
  moduleSpecifier = DEFAULT_SPECIFIER,
}: {
  introspection: Introspection;
  moduleSpecifier?: string;
}): string {
  const tables = Object.keys(introspection).sort();
  return `// Code generated by apigen. DO NOT EDIT.

import {
  Apigen as ApigenBase,
  type DbInput,
  type Relation,
  relation as relationBase,
} from '${moduleSpecifier}';

export const catalog = {
${catalogLiteral({ introspection, tables })}
} as const;

export type Catalog = typeof catalog;

${rowTypes({ introspection, tables })}

type ColumnsOf<R extends keyof Catalog> = Extract<keyof Catalog[R], string>;

export function relation<R extends keyof Catalog & string>(name: R): Relation<ColumnsOf<R>> {
  return relationBase<ColumnsOf<R>>(name);
}

export class Apigen extends ApigenBase {
  constructor(options: { db: DbInput }) {
    super({ db: options.db, catalog });
  }
}
`;
}
