// Code generated by apigen. DO NOT EDIT.

import {
  Apigen as ApigenBase,
  type DbInput,
  type Relation,
  relation as relationBase,
} from '@repo/apigen';

export const catalog = {
  category_summary: {
    category: 'text',
    product_count: 'int8',
    avg_price: 'numeric',
  },
  in_stock_products: {
    id: 'int8',
    name: 'text',
    category: 'text',
    price: 'numeric',
  },
  products: {
    id: 'int8',
    sku: 'text',
    name: 'text',
    category: 'text',
    price: 'numeric',
    in_stock: 'bool',
    added_on: 'date',
  },
} as const;

export type Catalog = typeof catalog;

export interface CategorySummary {
  category: string | null;
  product_count: string | null;
  avg_price: string | null;
}

export interface InStockProducts {
  id: string | null;
  name: string | null;
  category: string | null;
  price: string | null;
}

export interface Products {
  id: string;
  sku: string;
  name: string;
  category: string;
  price: string;
  in_stock: boolean;
  added_on: string;
}

type ColumnsOf<R extends keyof Catalog> = Extract<keyof Catalog[R], string>;

export function relation<R extends keyof Catalog & string>(name: R): Relation<ColumnsOf<R>> {
  return relationBase<ColumnsOf<R>>(name);
}

export class Apigen extends ApigenBase {
  constructor(options: { db: DbInput }) {
    super({ db: options.db, catalog });
  }
}
