// Code generated by apigen. DO NOT EDIT.

import {
  Apigen as ApigenBase,
  type DbInput,
  type Func,
  func as funcBase,
  type Relation,
  relation as relationBase,
} from '@repo/apigen';

export const catalog = {
  articles: {
    id: 'int8',
    slug: 'text',
    title: 'text',
    body: 'text',
    published: 'bool',
  },
} as const;

export type Catalog = typeof catalog;

export const functions = {
  greet: {
    name: 'text',
    excited: 'bool',
  },
  publish_article: {
    article_slug: 'text',
  },
  search_articles: {
    query: 'text',
  },
  server_time: {},
} as const;

export type Functions = typeof functions;

export interface Articles {
  id: string;
  slug: string;
  title: string;
  body: string;
  published: boolean;
}

type ColumnsOf<R extends keyof Catalog> = Extract<keyof Catalog[R], string>;

export function relation<R extends keyof Catalog & string>(name: R): Relation<ColumnsOf<R>> {
  return relationBase<ColumnsOf<R>>(name);
}

export function func<F extends keyof Functions & string>(name: F): Func {
  return funcBase(name);
}

export class Apigen extends ApigenBase {
  constructor(options: { db: DbInput }) {
    super({ db: options.db, catalog, functions });
  }
}
